package org.citrus.learn.paymentsservice.entity;

import java.util.UUID;

import org.springframework.data.annotation.Id;
import org.springframework.data.domain.Persistable;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Table(name = "transactions")
public class Transaction implements Persistable<UUID> {

	@Id
	@Column("id")
	private UUID id;

	@Column("status")
	private TransactionStatus status;

	@Override
	public boolean isNew() {
		// Transactions are immutable, IDs are generated by clients
		return true;
	}
}
