apiVersion: v1
kind: Service
metadata:
  name: positions-service
  namespace: trading-system
spec:
  selector:
    app: positions-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP
