apiVersion: apps/v1
kind: Deployment
metadata:
  name: wire-mock
  namespace: trading-system
  annotations:
    kubernetes.io/change-cause: "Image updated to latest"
  labels:
    app: wire-mock
spec:
  progressDeadlineSeconds: 10
  revisionHistoryLimit: 100
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 1
  replicas: 3
  selector:
    matchLabels:
      app: wire-mock
  template:
    metadata:
      name: wire-mock
      labels:
        app: wire-mock
    spec:
      containers:
        - name: wire-mock
          image: wiremock/wiremock:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
